version: "2"
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
  redis:
    image: redis
    ports:
      - "6379:6379"
  consumer1:
    build: .
    environment:
      - CONSUMER_NAME=consumer1
  consumer2:
    build: .
    environment:
      - CONSUMER_NAME=consumer2
  consumer3:
    build: .
    environment:
      - CONSUMER_NAME=consumer3
