version: "2"
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
  consumer1:
    build: .
    environment:
      - CONSUMER_NAME=consumer1
  consumer2:
    build: .
    environment:
      - CONSUMER_NAME=consumer2
  consumer3:
    build: .
    environment:
      - CONSUMER_NAME=consumer3
